### ISSUE TITLE
Test Not Passing

### ISSUE THREAD

**Issue by ahill01** [learn-co-curriculum/phase-1-fetch-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/4999/assignments/165576?module_item_id=357381

### Concern

The output is correct on the DOM but the "renders book titles into the DOM by passing a JSON object to renderBooks()" test is not passing. 

### Additional Context

<img width="1424" alt="Screen Shot 2022-03-02 at 8 29 04 AM" src="https://user-images.githubusercontent.com/31513177/156381202-c5fb65bb-ed47-4351-b104-b55311cd6bd4.png">

**Comment by lizbur10** [comment]
Thanks for raising this issue. Based on your error, it looks like the issue may be
related to your code rather than with the lesson itself or the instructions. The 
curriculum team monitors these issues so that we can fix typos and bugs in 
the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!

**Comment by lizbur10** [comment]
Hi there! The issue here is that you aren't returning the fetch - see the Note near the bottom of the lesson, and the comment at the top of the index.js file. All you need to do is add the `return` keyword in front of `fetch` 😃

**Comment by ahill01** [comment]
Thank you!

Best,
Allison
